# Generated by Django 5.0 on 2023-12-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_kelompok_buku_kelompok_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='Kelompok_id',
        ),
    ]
