# Generated by Django 5.0 on 2023-12-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_remove_buku_kelompok_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='Kelompok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.kelompok'),
        ),
    ]
